added files

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,9 +36,6 @@ jobs:
       - name: Build the app
         run: npm run build --verbose
 
-      - name: Debug - List all project files
-        run: ls -alh ${{ github.workspace }}
-
       - name: Log in to Docker Hub
         run: |
           for i in {1..3}; do
@@ -135,7 +132,7 @@ jobs:
           aws ecs update-service \
             --cluster my-ecs-cluster \
             --service my-ecs-service \
-            --task-definition $TASK_DEF_ARN
+            --task-definition $TASK_DEF_ARN || (echo "❌ ERROR: Update failed!" && exit 1)
 
       - name: Wait for Service to Stabilize
         run: |
